apiVersion: apps/v1
kind: Deployment
metadata:
  name: gaserver-deployment
  labels:
    app: gaserver
spec:
  replicas: {{ .Values.gaserverreplica }}
  selector:
    matchLabels:
      app-name: gaserver
  template:
    metadata:
      labels:
        app-name: gaserver
    spec:
      containers:
      - name: gaserver-container
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
        image: {{ .Values.gaserverdockerimage }}
        imagePullPolicy: Always
        ports:
        - containerPort: 9090
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: gaserver-hpa
  labels:
    creator: gaserver
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: gaserver-deployment
  targetCPUUtilizationPercentage: 30
  minReplicas: 1
  maxReplicas: 100
---
apiVersion: v1
kind: Service
metadata:
  name: gaserver-svc
  labels:
    creator: gaserver
spec:
  type: ClusterIP
  ports:
    - name: gaserver-ingress
      port: 9090
  selector:
    app-name: gaserver