apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginxapp-ingress
  namespace: default
  annotations:
spec:
  rules:
    - host: {{ .Values.domain }}
      http:
        paths:
          - path: /
            backend:
              serviceName: gaserver-svc
              servicePort: 9090
